The following questions concern a small snapshot of top-of-book data in futures markets
and ask you to consider implied orders and trades. Without showing all contracts that imply
into these markets and without showing the market-by-order data and knowing the matching algorithms,
it is impossible to say with certainty what limit orders get filled. Instead, these questions
ask whether it is possible to get filled. You do not need to determine actual fills.

You should show your work, but it does not need to be code. You _can_ code a solution, but you
could simply present your answer in a markdown cell or write out your solutions in another document.

In [1]:
import pandas as pd

top_of_book = pd.DataFrame(
    [
        {
            "symbol": "SR3H6",
            "bid_sz_00": 431,
            "bid_px_00": 96.6,
            "ask_px_00": 96.605,
            "ask_sz_00": 2190,
        },
        {
            "symbol": "SR3U7",
            "bid_sz_00": 5563,
            "bid_px_00": 96.96,
            "ask_px_00": 96.965,
            "ask_sz_00": 52,
        },
        {
            "symbol": "SR3H6-SR3U7",
            "bid_sz_00": 7,
            "bid_px_00": -37,
            "ask_px_00": -36,
            "ask_sz_00": 7,
        },
    ]
)
top_of_book

symbol  bid_sz_00  bid_px_00  ask_px_00  ask_sz_00
0        SR3H6        431      96.60     96.605       2190
1        SR3U7       5563      96.96     96.965         52
2  SR3H6-SR3U7          7     -37.00    -36.000          7

1. What are the bid and ask, price and size, in the spread market implied IN by the outright legs?

### Answer 1: Implied bid and ask in the spread market from the outright legs

**Spread Definition:** Spread = SR3H6 - SR3U7

**Calculating the Implied Bid (to buy the spread):**
- To buy the spread: buy SR3H6, sell SR3U7
- Use SR3H6 ask price (96.605) and SR3U7 bid price (96.96)
- Implied bid = 96.605 - 96.96 = **-0.355**
- Implied bid size = min(2190, 5563) = **2190**

**Calculating the Implied Ask (to sell the spread):**
- To sell the spread: sell SR3H6, buy SR3U7
- Use SR3H6 bid price (96.60) and SR3U7 ask price (96.965)
- Implied ask = 96.60 - 96.965 = **-0.365**
- Implied ask size = min(431, 52) = **52**

**Conclusion:**
- Implied bid: **-0.355 @ 2190**
- Implied ask: **-0.365 @ 52**

**Note:** The direct spread market quotes are bid: -37.00 @ 7, ask: -36.00 @ 7. The difference between direct and implied prices suggests potential arbitrage opportunities.


2. If a market order sells 5 spreads, what price will trade? Could it be implied in the legs?

### Answer 2: Market order selling 5 spreads

When a market order sells 5 spreads, it will trade at the best available bid price.

**Analysis of possible execution prices:**

1. **Direct spread market bid:** -37.00 @ 7
   - Sufficient liquidity to fill all 5 contracts

2. **Implied bid (via outright legs):** -0.355 @ 2190
   - By buying SR3H6 (96.605) and selling SR3U7 (96.96)
   - Sufficient liquidity to fill all 5 contracts

**Execution Price:** 
- The direct spread market bid (-37.00) is lower (worse for the seller) than the implied bid (-0.355)
- The exchange matching algorithm prioritizes the best price for the trader
- Therefore, the **execution price should be -0.355** (or close to it)

**Could it be an implied trade?**
- **Yes**, it is very likely to be an implied trade
- Because the implied bid (-0.355) is better than the direct spread market bid (-37.00)
- The exchange will decompose these 5 spreads into outright legs and execute them in the SR3H6 and SR3U7 markets

**Practical considerations:**
In actual trading, possible execution scenarios:
- Entirely through implied market (most likely)
- Partially in direct market, partially in implied market
- Depends on the exchange's matching algorithm and real-time order book state


3. If a market order buys 5 spreads, what price will trade? Could it be implied in the legs?

### Answer 3: Market order buying 5 spreads

When a market order buys 5 spreads, it will trade at the best available ask price.

**Analysis of possible execution prices:**

1. **Direct spread market ask:** -36.00 @ 7
   - Sufficient liquidity to fill all 5 contracts

2. **Implied ask (via outright legs):** -0.365 @ 52
   - By selling SR3H6 (96.60) and buying SR3U7 (96.965)
   - Sufficient liquidity to fill 5 contracts (limited to 52)

**Execution Price:**
- The direct spread market ask (-36.00) is lower (better for the buyer) than the implied ask (-0.365)
- Therefore, the **execution price should be -36.00**

**Could it be an implied trade?**
- **Unlikely** to be an implied trade
- Because the direct spread market ask (-36.00) is better than the implied ask (-0.365)
- The exchange matching algorithm prioritizes the best price for the trader
- These 5 contracts should execute directly in the spread market, not through outright legs

**Conclusion:**
- Execution price: **-36.00**
- Execution method: Direct spread market (not implied)
- After execution, the spread market ask order will have 7 - 5 = 2 contracts remaining


In [ ]:
# Verification: Questions 1-3 Implied Price Calculations

import pandas as pd

# Market data
print("=" * 60)
print("Questions 1-3: SR3H6-SR3U7 Spread Analysis")
print("=" * 60)

sr3h6_bid, sr3h6_ask = 96.60, 96.605
sr3h6_bid_sz, sr3h6_ask_sz = 431, 2190

sr3u7_bid, sr3u7_ask = 96.96, 96.965
sr3u7_bid_sz, sr3u7_ask_sz = 5563, 52

spread_bid, spread_ask = -37.00, -36.00
spread_bid_sz, spread_ask_sz = 7, 7

# Calculate implied prices
# Spread = SR3H6 - SR3U7
implied_spread_bid = sr3h6_ask - sr3u7_bid  # To buy spread: buy H6, sell U7
implied_spread_ask = sr3h6_bid - sr3u7_ask  # To sell spread: sell H6, buy U7

implied_spread_bid_sz = min(sr3h6_ask_sz, sr3u7_bid_sz)
implied_spread_ask_sz = min(sr3h6_bid_sz, sr3u7_ask_sz)

print(f"\nDirect Spread Market:")
print(f"  Bid: {spread_bid:.3f} @ {spread_bid_sz}")
print(f"  Ask: {spread_ask:.3f} @ {spread_ask_sz}")

print(f"\nImplied Spread (via outright legs):")
print(f"  Implied Bid: {implied_spread_bid:.3f} @ {implied_spread_bid_sz}")
print(f"  Implied Ask: {implied_spread_ask:.3f} @ {implied_spread_ask_sz}")

print(f"\nQuestion 2 - Selling 5 spreads:")
best_bid = max(spread_bid, implied_spread_bid)
print(f"  Best Bid: {best_bid:.3f}")
print(f"  Execution: {'Implied Market' if best_bid == implied_spread_bid else 'Direct Market'}")

print(f"\nQuestion 3 - Buying 5 spreads:")
best_ask = min(spread_ask, implied_spread_ask)
print(f"  Best Ask: {best_ask:.3f}")
print(f"  Execution: {'Implied Market' if best_ask == implied_spread_ask else 'Direct Market'}")


In [3]:
top_of_book = pd.DataFrame(
    [
        {
            "symbol": "ZSX5",
            "bid_sz_00": 23,
            "bid_px_00": 1008.5,
            "ask_px_00": 1008.75,
            "ask_sz_00": 46,
        },
        {
            "symbol": "ZSF6",
            "bid_sz_00": 72,
            "bid_px_00": 1026.25,
            "ask_px_00": 1026.5,
            "ask_sz_00": 84,
        },
        {
            "symbol": "ZSH6",
            "bid_sz_00": 16,
            "bid_px_00": 1041.75,
            "ask_px_00": 1042,
            "ask_sz_00": 8,
        },
        {
            "symbol": "ZSX5-ZSF6",
            "bid_sz_00": 4141,
            "bid_px_00": -18,
            "ask_px_00": -17.75,
            "ask_sz_00": 2187,
        },
        {
            "symbol": "ZSF6-ZSH6",
            "bid_sz_00": 348,
            "bid_px_00": -15.5,
            "ask_px_00": -15.25,
            "ask_sz_00": 1167,
        },
    ]
)
top_of_book

symbol  bid_sz_00  bid_px_00  ask_px_00  ask_sz_00
0       ZSX5         23    1008.50    1008.75         46
1       ZSF6         72    1026.25    1026.50         84
2       ZSH6         16    1041.75    1042.00          8
3  ZSX5-ZSF6       4141     -18.00     -17.75       2187
4  ZSF6-ZSH6        348     -15.50     -15.25       1167

### Answer 4: Best implied bid and offer in ZSF6 from spreads and other legs

ZSF6 can be implied through two spreads:
1. ZSX5-ZSF6 spread: ZSF6 = ZSX5 - (ZSX5-ZSF6)
2. ZSF6-ZSH6 spread: ZSF6 = ZSH6 + (ZSF6-ZSH6)

**Implied ZSF6 bid via ZSX5-ZSF6 spread:**
- To buy ZSF6: buy ZSX5, sell (ZSX5-ZSF6) spread
- ZSF6 implied bid = ZSX5 ask - (ZSX5-ZSF6) ask
- = 1008.75 - (-17.75) = 1008.75 + 17.75 = **1026.50**
- Implied bid size = min(46, 2187) = **46**

**Implied ZSF6 ask via ZSX5-ZSF6 spread:**
- To sell ZSF6: sell ZSX5, buy (ZSX5-ZSF6) spread
- ZSF6 implied ask = ZSX5 bid - (ZSX5-ZSF6) bid
- = 1008.50 - (-18.00) = 1008.50 + 18.00 = **1026.50**
- Implied ask size = min(23, 4141) = **23**

**Implied ZSF6 bid via ZSF6-ZSH6 spread:**
- To buy ZSF6: buy (ZSF6-ZSH6) spread, sell ZSH6
- ZSF6 implied bid = (ZSF6-ZSH6) ask + ZSH6 bid
- = -15.25 + 1041.75 = **1026.50**
- Implied bid size = min(1167, 16) = **16**

**Implied ZSF6 ask via ZSF6-ZSH6 spread:**
- To sell ZSF6: sell (ZSF6-ZSH6) spread, buy ZSH6
- ZSF6 implied ask = (ZSF6-ZSH6) bid + ZSH6 ask
- = -15.50 + 1042.00 = **1026.50**
- Implied ask size = min(348, 8) = **8**

**Summary:**
- **Best implied bid: 1026.50**, available size: **46** (via ZSX5-ZSF6)
- **Best implied ask: 1026.50**, available size: **23** (via ZSX5-ZSF6)

**Comparison with direct market:**
- Direct market: bid: 1026.25 @ 72, ask: 1026.50 @ 84
- Implied bid (1026.50) equals the direct market ask
- Implied ask (1026.50) is higher than the direct market bid (1026.25)

This indicates highly efficient market pricing, with implied prices closely aligned with direct market prices.


4. What is the best bid and offer, price and size,
implied OUT in the `ZSF6` market by each of the spreads and other legs?

5. Suppose a market order sells 5 `ZSF6`. At what price is the order filled? Is the fill potentially
an implied trade?

### Answer 5: Market order selling 5 ZSF6

When a market order sells 5 ZSF6, it will trade at the best available bid price.

**Possible execution price sources:**

1. **Direct market bid:** 1026.25 @ 72
   - Sufficient liquidity to fill all 5 contracts

2. **Implied bid (via ZSX5-ZSF6):** 1026.50 @ 46
   - Buy ZSX5 (1008.75), sell ZSX5-ZSF6 spread (-17.75)
   - Sufficient liquidity to fill all 5 contracts

3. **Implied bid (via ZSF6-ZSH6):** 1026.50 @ 16
   - Buy ZSF6-ZSH6 spread (-15.25), sell ZSH6 (1041.75)
   - Sufficient liquidity to fill all 5 contracts

**Execution Price:**
- The implied bid (1026.50) is higher (better for the seller) than the direct market bid (1026.25)
- The exchange matching algorithm prioritizes the best price for the trader
- Therefore, the **execution price should be 1026.50**

**Is the fill potentially an implied trade?**
- **Yes, very likely to be an implied trade**
- Because the implied bid (1026.50) is better than the direct market bid (1026.25)
- These 5 contracts could be filled through:
  - Via ZSX5-ZSF6 spread (more likely, due to better liquidity: 46 vs 16)
  - Via ZSF6-ZSH6 spread
  - Or a combination of both

**Most likely execution path:**
Implied trade via ZSX5-ZSF6 spread, as this path has greater available size (46 contracts).


6. Suppose a market order buys 5 `ZSF6`. At what price is the order filled? Is the fill potentially
an implied trade?

### Answer 6: Market order buying 5 ZSF6

When a market order buys 5 ZSF6, it will trade at the best available ask price.

**Possible execution price sources:**

1. **Direct market ask:** 1026.50 @ 84
   - Sufficient liquidity to fill all 5 contracts

2. **Implied ask (via ZSX5-ZSF6):** 1026.50 @ 23
   - Sell ZSX5 (1008.50), buy ZSX5-ZSF6 spread (-18.00)
   - Sufficient liquidity to fill all 5 contracts

3. **Implied ask (via ZSF6-ZSH6):** 1026.50 @ 8
   - Sell ZSF6-ZSH6 spread (-15.50), buy ZSH6 (1042.00)
   - Sufficient liquidity to fill all 5 contracts

**Execution Price:**
- The direct market ask (1026.50) **equals** the implied ask (1026.50)
- Therefore, the **execution price is 1026.50**

**Is the fill potentially an implied trade?**
- **Possibly, but not necessarily**
- Since the direct market and implied market prices are identical, the exchange could execute through either path
- Possible execution scenarios:
  1. Entirely in the direct market (simplest approach)
  2. Entirely through implied market
  3. Partially in direct market, partially in implied market

**Practical considerations:**
- Since the direct market has greater liquidity (84 vs 23 vs 8) and the price is identical
- **Most likely to execute in the direct market**
- However, if the direct market orders are consumed by other trades, it could execute through implied markets

**Key observation:**
This example demonstrates market efficiency: when direct and implied market prices align, it indicates effective pricing with arbitrage opportunities eliminated.


In [ ]:
# Verification: Questions 4-6 Implied Price Calculations

print("\n" + "=" * 60)
print("Questions 4-6: ZSF6 Implied Price Analysis")
print("=" * 60)

# Market data
zsx5_bid, zsx5_ask = 1008.50, 1008.75
zsx5_bid_sz, zsx5_ask_sz = 23, 46

zsf6_bid, zsf6_ask = 1026.25, 1026.50
zsf6_bid_sz, zsf6_ask_sz = 72, 84

zsh6_bid, zsh6_ask = 1041.75, 1042.00
zsh6_bid_sz, zsh6_ask_sz = 16, 8

spread1_bid, spread1_ask = -18.00, -17.75  # ZSX5-ZSF6
spread1_bid_sz, spread1_ask_sz = 4141, 2187

spread2_bid, spread2_ask = -15.50, -15.25  # ZSF6-ZSH6
spread2_bid_sz, spread2_ask_sz = 348, 1167

print(f"\nDirect ZSF6 Market:")
print(f"  Bid: {zsf6_bid:.2f} @ {zsf6_bid_sz}")
print(f"  Ask: {zsf6_ask:.2f} @ {zsf6_ask_sz}")

# Implied ZSF6 via ZSX5-ZSF6
# ZSF6 = ZSX5 - (ZSX5-ZSF6)
implied_zsf6_bid_via_spread1 = zsx5_ask - spread1_ask
implied_zsf6_ask_via_spread1 = zsx5_bid - spread1_bid
implied_zsf6_bid_sz_via_spread1 = min(zsx5_ask_sz, spread1_ask_sz)
implied_zsf6_ask_sz_via_spread1 = min(zsx5_bid_sz, spread1_bid_sz)

print(f"\nImplied ZSF6 via ZSX5-ZSF6:")
print(f"  Implied Bid: {implied_zsf6_bid_via_spread1:.2f} @ {implied_zsf6_bid_sz_via_spread1}")
print(f"  Implied Ask: {implied_zsf6_ask_via_spread1:.2f} @ {implied_zsf6_ask_sz_via_spread1}")

# Implied ZSF6 via ZSF6-ZSH6
# ZSF6 = ZSH6 + (ZSF6-ZSH6)
implied_zsf6_bid_via_spread2 = spread2_ask + zsh6_bid
implied_zsf6_ask_via_spread2 = spread2_bid + zsh6_ask
implied_zsf6_bid_sz_via_spread2 = min(spread2_ask_sz, zsh6_bid_sz)
implied_zsf6_ask_sz_via_spread2 = min(spread2_bid_sz, zsh6_ask_sz)

print(f"\nImplied ZSF6 via ZSF6-ZSH6:")
print(f"  Implied Bid: {implied_zsf6_bid_via_spread2:.2f} @ {implied_zsf6_bid_sz_via_spread2}")
print(f"  Implied Ask: {implied_zsf6_ask_via_spread2:.2f} @ {implied_zsf6_ask_sz_via_spread2}")

# Best implied prices
best_implied_bid = max(implied_zsf6_bid_via_spread1, implied_zsf6_bid_via_spread2)
best_implied_ask = min(implied_zsf6_ask_via_spread1, implied_zsf6_ask_via_spread2)

print(f"\nBest Implied Prices:")
print(f"  Best Implied Bid: {best_implied_bid:.2f}")
print(f"  Best Implied Ask: {best_implied_ask:.2f}")

print(f"\nQuestion 5 - Selling 5 ZSF6:")
overall_best_bid = max(zsf6_bid, best_implied_bid)
print(f"  Best Bid: {overall_best_bid:.2f}")
if overall_best_bid == zsf6_bid:
    print(f"  Execution: Direct Market")
else:
    print(f"  Execution: Implied Market")
    if best_implied_bid == implied_zsf6_bid_via_spread1:
        print(f"  Implied Path: via ZSX5-ZSF6")
    else:
        print(f"  Implied Path: via ZSF6-ZSH6")

print(f"\nQuestion 6 - Buying 5 ZSF6:")
overall_best_ask = min(zsf6_ask, best_implied_ask)
print(f"  Best Ask: {overall_best_ask:.2f}")
if overall_best_ask == zsf6_ask and overall_best_ask == best_implied_ask:
    print(f"  Execution: Direct and Implied markets have same price, could be either")
elif overall_best_ask == zsf6_ask:
    print(f"  Execution: Direct Market")
else:
    print(f"  Execution: Implied Market")
    if best_implied_ask == implied_zsf6_ask_via_spread1:
        print(f"  Implied Path: via ZSX5-ZSF6")
    else:
        print(f"  Implied Path: via ZSF6-ZSH6")
